// resources/assets/react/components/Footer.jsx
import React from 'react'

export default class Footer extends React.Component{
	render(){
		return (
            <footer className="footer">
                <div className="container">
                    <ul className="nav navbar-nav footer-nav">
                    <li className="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                  </ul>
                </div>
            </footer>
			)
	}
}

// resources/assets/js/components/user-page/footer-vue.vue
<template>
    <footer class="footer">
        <div class="container">
            <ul class="nav navbar-nav footer-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>
    </footer>
</template>

<script>
	export default{
		name: 'Footer-Vue'
	}
</script>
