// resources/assets/js/components/user-page/breadcrumb-vue.vue
<template>
	<aside class="col-md-12 col-xs-12 col-lg-12">
        <aside class="breadcrumb-item">
            <ul class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">Products</a></li>
                <li class="active">Accessories</li>
            </ul>
        </aside>
    </aside>
</template>

<script>
	export default{
		name: "Breadcrumb-Vue"
	}
</script>

// resources/assets/react/components/Breadcrumb.jsx
import React from 'react'

export default class Breadcrumb extends React.Component{

	render(){
		return (
			<aside className="col-md-12 col-xs-12 col-lg-12">
		        <aside className="breadcrumb-item">
		            <ul className="breadcrumb">
		                {this.props.children}
		            </ul>
		        </aside>
		    </aside>
			)
	}
}
